### ISSUE TITLE
Fail to run code on now.sh

### ISSUE THREAD

**Issue by sync** [anmonteiro/github-stars-lambda-demo#2]
It was nice meeting you at reasonconf and your presentation was great, which got me interested in trying this project.

I tried to run the `./build.sh` script then running `now`, and then opening the url on a browser `https://github-stars.dblechoc.now.sh/?repo=sync/hackerz`. But all I get is:

```
502: An error occurred with your deployment

Code: NO_STATUS_CODE_FROM_LAMBDA
```
I made the deployment public at: https://github-stars.dblechoc.now.sh

Also looking at the logs i get this: Fatal error: exception Not_found

**Comment by anmonteiro** [comment]
You need to follow the instructions in the readme and add your github token

**Comment by sync** [comment]
right thanks I forgot :-)

**Comment by sync** [comment]
It worked 👍
